# Generated by Django 5.1.6 on 2025-04-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre',
            new_name='nombres',
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(default='V', max_length=100),
            preserve_default=False,
        ),
    ]
