# Generated by Django 5.1.6 on 2025-04-29 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_api', '0002_rename_nombre_usuario_nombres_usuario_apellidos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='usario',
            new_name='usuario',
        ),
    ]
