# Generated by Django 5.1.6 on 2025-04-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_api', '0003_rename_usario_funcionario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipotramite',
            name='abreviado',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='tipotramite',
            name='tiempo_espera',
            field=models.IntegerField(blank=True, default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='tipoturno',
            name='abreviado',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='tipoturno',
            name='tiempo_espera',
            field=models.IntegerField(blank=True, default=0, max_length=3),
        ),
    ]
