# Generated by Django 5.1.6 on 2025-04-30 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_api', '0004_tipotramite_abreviado_tipotramite_tiempo_espera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='id_ventanilla',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='atencion_ventanilla', to='turnos_api.ventanila'),
            preserve_default=False,
        ),
    ]
