# Generated by Django 5.1.6 on 2025-05-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_api', '0005_atencion_id_ventanilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipotramite',
            name='color',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tipotramite',
            name='icono',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tipoturno',
            name='color',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tipoturno',
            name='icono',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
