# Generated by Django 5.1.6 on 2025-05-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_api', '0006_tipotramite_color_tipotramite_icono_tipoturno_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipotramite',
            name='tiempo_espera',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tipoturno',
            name='tiempo_espera',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
