# Generated by Django 5.1.6 on 2025-05-08 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_api', '0006_tipotramite_color_tipotramite_icono_tipoturno_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='password',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipotramite',
            name='tiempo_espera',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tipoturno',
            name='tiempo_espera',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
