# Generated by Django 5.1.6 on 2025-05-08 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_api', '0007_alter_tipotramite_tiempo_espera_and_more'),
        ('turnos_api', '0007_remove_funcionario_email_remove_funcionario_nombre_and_more'),
    ]

    operations = [
    ]
