# Generated by Django 5.1.6 on 2025-05-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_api', '0008_merge_20250508_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='puesto',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
