# Generated by Django 5.1.6 on 2025-05-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_api', '0009_puesto_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='fecha_fin_atencion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
