# Generated by Django 5.1.6 on 2025-06-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_api', '0010_atencion_fecha_fin_atencion'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='atencion',
            index=models.Index(fields=['id_ventanilla'], name='turnos_api__id_vent_8f3a8c_idx'),
        ),
        migrations.AddIndex(
            model_name='atencion',
            index=models.Index(fields=['id_funcionario'], name='turnos_api__id_func_a0213d_idx'),
        ),
        migrations.AddIndex(
            model_name='atencion',
            index=models.Index(fields=['fecha_atencion'], name='turnos_api__fecha_a_1dcfa2_idx'),
        ),
        migrations.AddIndex(
            model_name='atencion',
            index=models.Index(fields=['fecha_fin_atencion'], name='turnos_api__fecha_f_2c6419_idx'),
        ),
        migrations.AddIndex(
            model_name='puesto',
            index=models.Index(fields=['fecha_salida'], name='turnos_api__fecha_s_1401c7_idx'),
        ),
        migrations.AddIndex(
            model_name='puesto',
            index=models.Index(fields=['id_ventanilla'], name='turnos_api__id_vent_20fcc1_idx'),
        ),
        migrations.AddIndex(
            model_name='puesto',
            index=models.Index(fields=['id_funcionario'], name='turnos_api__id_func_77ac95_idx'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['estado'], name='turnos_api__estado__b25895_idx'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['fecha_turno'], name='turnos_api__fecha_t_3a6f6f_idx'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['id_usuario'], name='turnos_api__id_usua_6ab337_idx'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['tipo_turno'], name='turnos_api__tipo_tu_e2336c_idx'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['tipo_tramite'], name='turnos_api__tipo_tr_622260_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['cedula'], name='turnos_api__cedula_d9a92b_idx'),
        ),
    ]
