# Generated by Django 5.1.6 on 2025-07-02 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_api', '0011_atencion_turnos_api__id_vent_8f3a8c_idx_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ventanila',
            new_name='Ventanilla',
        ),
    ]
