# Generated by Django 5.1.6 on 2026-02-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_api', '0012_rename_ventanila_ventanilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='discapacidad',
            field=models.CharField(blank=True, choices=[('NING', 'Ninguna'), ('FIS', 'Física'), ('AUD', 'Auditiva'), ('VIS', 'Visual'), ('COG', 'Cognitiva'), ('PSI', 'Psicosocial'), ('MUL', 'Múltiple'), ('NI', 'No informa')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='etnia',
            field=models.CharField(blank=True, choices=[('IND', 'Indígena'), ('ROM', 'ROM (Gitano)'), ('RAI', 'Raizal'), ('PAL', 'Palenquero'), ('AFRO', 'Afrocolombiano'), ('NING', 'Ninguno'), ('NI', 'No informa')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No binario'), ('O', 'Otro'), ('NI', 'No informa')], max_length=2, null=True),
        ),
    ]
